### ISSUE TITLE
Hamburger Menu is broken

### ISSUE THREAD

**Issue by bendisposto** [rheinjug/website#2]

**Comment by bendisposto** [comment]
@n2o Magst du mal schauen?

**Comment by n2o** [comment]
Sicher

**Comment by n2o** [comment]
Jquery kann nicht asynchron geladen werden, da es sonst nicht notwendigerweise schon geladen ist, wenn bootstrap versucht der navbar das onClick zuzuweisen. Ohne `async` blockt das Laden der Seite, was aber notwendig ist, damit die Funktionalitäten nach und nach geladen werden können.
